providers:
#  - file://http-provider.yaml
  - file://ws-provider.yaml

scenarios:
  - file://scenarios/chat-memory.yaml
  - file://scenarios/time.yaml
  - file://scenarios/stocks.yaml
  - file://scenarios/moderation.yaml
